import { NgModule } from '@angular/core';
import {MatTooltipModule} from '@angular/material/tooltip';

import {
  MatButtonModule,
  MatCheckboxModule,
  MatToolbarModule,
  MatIconModule,
  MatMenuModule,
  MatCardModule,
  MatTabsModule,
  MatGridListModule,
  MatProgressSpinnerModule,
  MatInputModule,
  MatSelectModule,
  MatSortModule,
  MatTableModule,
  MatChipsModule,
  MatFormFieldModule,
  MatSnackBarModule,
  MatExpansionModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatStepperModule,
  MatDividerModule,
  MatListModule,
  MatDialogModule,
  MatSidenavModule,
  MatRadioModule
} from '@angular/material';

@NgModule({
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatIconModule,
    MatMenuModule,
    MatCardModule,
    MatTabsModule,
    MatGridListModule,
    MatProgressSpinnerModule,
    MatInputModule,
    MatSelectModule,
    MatSortModule,
    MatTableModule,
    MatChipsModule,
    MatFormFieldModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatStepperModule,
    MatDividerModule,
    MatListModule,
    MatDialogModule,
    MatSidenavModule,
    MatTooltipModule,
    MatRadioModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatIconModule,
    MatMenuModule,
    MatCardModule,
    MatTabsModule,
    MatGridListModule,
    MatProgressSpinnerModule,
    MatInputModule,
    MatSelectModule,
    MatSortModule,
    MatTableModule,
    MatChipsModule,
    MatFormFieldModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatStepperModule,
    MatDividerModule,
    MatListModule,
    MatDialogModule,
    MatSidenavModule,
    MatTooltipModule,
    MatRadioModule
  ]
})
export class MaterialModule { }
